# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'GoStream' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GoStream
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'

  

  #pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  #pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  #pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  #pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  #pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNIap', :path => '../node_modules/react-native-iap'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

end

